# URL для отправки данных на сервер
# Этот URL используется для отправки JSON-запросов с информацией об игроках (время игры, количество дней и т.д.).
# Убедитесь, что указываете правильный URL вашего сервера, который принимает данные от Minecraft.
api-url: "http://ttt.ru/api.php"

# Интервал в тиках для обновления данных
# Интервал определяет, как часто будут обновляться и отправляться данные на сервер.
# 20 тиков = 1 секунда. Например, 600 тиков = 30 секунд.
# Рекомендуется выбирать интервал с учётом нагрузки на сервер и частоты обновлений.
update-interval-ticks: 600 # 600 тиков = 30 секунд

# API-токен для аутентификации
# Этот токен используется для проверки подлинности запросов к серверу.
# Передаваемый с запросом токен позволит убедиться, что данные отправляются с доверенного источника.
# Замените 'your-secure-api-token' на свой собственный токен для безопасности.
api-token: "your-secure-api-token"

